version: '3'
services:

  frontend:
    image: blossomlabsio/bloom-frontend
    env_file:
      - .env  
    depends_on:
      - postgres
      - backend
    container_name: bloom-frontend
    ports: 
      - "80:80"
        

  backend:
    image: blossomlabsio/bloom-backend

    depends_on:
      - postgres
    container_name: bloom-backend
    ports:
      - "8000:8000" 
    env_file:
      - .env

  postgres:
    image: postgres:latest
    env_file:
      - .env
    expose:
      - "5432:5432"
    volumes:
      - bloom_data:/var/lib/postgresql/data

volumes:
   bloom_data: 
     
    
