version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: blossomlabsio/bloom-backend
    depends_on:
      - postgres
    container_name: bloom-backend

    ports:
      - "8000:8000" 
    env_file:
      - .env

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - bloom_data:/var/lib/postgresql/data

volumes:
   bloom_data: 
     
    
